# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Detection of DNA base modification using nanopore sequencing
description:      'In this comprehensive two-day course, participants will learn how to use nanopore sequencing to detect DNA base modifications'
url:              https://sathish-t.github.io/nanopore-mod-course
baseurl:          /nanopore-mod-course
email:            sathish.thiyagarajan@earlham.ac.uk
feedbackurl:      https://docs.google.com/forms/d/e/1FAIpQLSexsorpRrVaKZ2Am-dSf9QcivNkrF0_S7X0oeHk2rcJKx3kNA/viewform
author:
  name:           'Sathish Thiyagarajan'
  url:            https://twitter.com/unintegrable

github:
  repo:           https://github.com/sathish-t/nanopore-mod-course
  #               Be sure the 'Issues' feature is activated in 'Settings'

plugins:
  - jekyll-sitemap
